name: CI
on:
  push:
    branches:
      - 'release-*'
  pull_request:
    branches:
      - main
      - 'release-*'

env:
  K8S_VERSION: 1.27.1
permissions:
  contents: read
  pull-requests: read

jobs:
  trivy:
    uses: "./.github/workflows/lib-trivy.yaml"

  validate:
    uses: "./.github/workflows/lib-validate.yaml"

  build:
    needs:
      - trivy
      - validate
    uses: "./.github/workflows/lib-build.yaml"

  e2e:
    needs:
      - build
    uses: "./.github/workflows/lib-e2e.yaml"
