name: Update demo bases
on:
  schedule:
    - cron: '0 0 1 * *' # once a month
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  demo_base_update:
    name: Create a PR for demo image updates
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Install frizbee
        run: |
          export FRIZBEE_HASH=cda91f86d0c96d0bc3c464c57a601ca414e0b2415372eb19b9a4c82fa3d4f802
          export FRIZBEE_VERSION=0.0.15

          mkdir /tmp/frizbee
          wget -q https://github.com/stacklok/frizbee/releases/download/v${FRIZBEE_VERSION}/frizbee_${FRIZBEE_VERSION}_linux_amd64.tar.gz -O /tmp/frizbee/frizbee.tar.gz
          cd /tmp/frizbee
          echo "$FRIZBEE_HASH frizbee.tar.gz" | sha256sum -c -
          tar xzf frizbee.tar.gz
          chmod +x /tmp/frizbee/frizbee
      - name: Run update script
        run: |
          export PATH=$PATH:/tmp/frizbee
          cd demo
          bash update-shas.sh
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # v6
        with:
          commit-message: "demo: update base images ${{ steps.date.outputs.date }}"
          title: "Update demo base images (${{ steps.date.outputs.date }})"
          token: ${{ secrets.GH_PR_TOKEN }}
          branch: demo-base-update-${{ steps.date.outputs.date }}
          body: >
            PR is auto-generated by GH action.



