name: Devel
on:
  schedule:
    - cron: '0 4 * * *'
  push:
    branches:
      - main
env:
  K8S_VERSION: 1.27.1
permissions:
  contents: read
  pull-requests: read

jobs:
  trivy:
    uses: "./.github/workflows/lib-trivy.yaml"

  validate:
    uses: "./.github/workflows/lib-validate.yaml"

  build:
    needs:
      - validate
      - trivy
    uses: "./.github/workflows/lib-build.yaml"

  # e2e:
  #   needs:
  #     - build
  #   uses: "./.github/workflows/lib-e2e.yaml"

  # devel image push
  publish:
    needs:
      #- e2e
      - build
    uses: "./.github/workflows/lib-publish.yaml"
    secrets: inherit
