name: publish
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image_tag:
        default: "devel"
        required: false
        type: string
      registry:
        default: "docker.io/intel"
        required: false
        type: string
env:
  no_base_check: "['intel-qat-plugin-kerneldrv', 'intel-idxd-config-initcontainer', 'crypto-perf', 'opae-nlb-demo']"

permissions:
  contents: read

jobs:
  image:
    name: Build image
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        image:
          #- intel-fpga-admissionwebhook
          # - intel-fpga-initcontainer
          # - intel-gpu-initcontainer
          - intel-gpu-plugin
          # - intel-fpga-plugin
          # - intel-qat-initcontainer
          # - intel-qat-plugin
          # - intel-deviceplugin-operator
          # - intel-sgx-admissionwebhook
          # - intel-sgx-plugin
          # - intel-sgx-initcontainer
          # - intel-dsa-plugin
          # - intel-iaa-plugin
          # - intel-idxd-config-initcontainer
          # - intel-dlb-plugin
          # - intel-dlb-initcontainer
          # - intel-xpumanager-sidecar

          # # Demo images
          #- crypto-perf
          #- opae-nlb-demo
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version-file: go.mod
          check-latest: true
      - run: make -e vendor
      - name: Build image
        env:
          IMAGE_NAME: ${{ matrix.image }}
        run: |
          ORG=${{ inputs.registry }} TAG=${{ inputs.image_tag }} make ${IMAGE_NAME} BUILDER=docker
      - name: List images
        run: docker images
      - name: Trivy scan for image
        uses: aquasecurity/trivy-action@6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8 # 0.24.0
        with:
          scan-type: image
          image-ref: ${{ inputs.registry }}/${{ matrix.image }}:${{ inputs.image_tag }}
          exit-code: 1
      - name: Test image base layer
        # Don't run base layer check for selected images
        if: ${{ !contains(fromJson(env.no_base_check), matrix.image) }}
        run: IMG=${{ inputs.registry }}/${{ matrix.image }}:${{ inputs.image_tag }} make test-image-base-layer BUILDER=docker
      - name: Login
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Extract Docker metadata
        if: ${{ inputs.image_tag != 'devel' }}
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ inputs.registry }}/${{ matrix.image }}:${{ inputs.image_tag }}
      - name: Push & Pull
        run: |
          docker push ${{ inputs.registry }}/${{ matrix.image }}:${{ inputs.image_tag }}
          docker pull ${{ inputs.registry }}/${{ matrix.image }}:${{ inputs.image_tag }}
      - name: Get image digest
        if: ${{ inputs.image_tag != 'devel' }}
        id: digest
        run: |
          echo "image_sha=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ inputs.registry }}/${{ matrix.image }}:${{ inputs.image_tag }})" >> $GITHUB_OUTPUT
      - name: Install cosign
        if: ${{ inputs.image_tag != 'devel' }}
        uses: sigstore/cosign-installer@v3.6.0
        with:
          cosign-release: 'v2.4.0'
      - name: Keyless image sign
        if: ${{ inputs.image_tag != 'devel' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.digest.outputs.image_sha }}
        run: |
          echo "${TAGS}"
          echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
        #run: |
        #  echo ${{ steps.digest.outputs.image_sha }}
        #  cosign sign --yes --rekor-url "https://rekor.sigstore.dev/" ${{ steps.digest.outputs.image_sha }}
      #- name: Verify the image signing
      #  run: |
      #    cosign verify  --rekor-url "https://rekor.sigstore.dev/" ${{ steps.digest.outputs.image_sha }} --certificate-identity "https://github.com/saintmalik/sign-container-images/.github/workflows/keyless.yaml@refs/heads/main" --certificate-oidc-issuer "https://token.actions.githubusercontent.com" | jq .
