name: e2e
on:
  workflow_call:

permissions:
  contents: read

jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: e2e-dsa-gnr
            targetjob: e2e-dsa
            runner: simics-gnr
            images: intel-dsa-plugin intel-idxd-config-initcontainer accel-config-demo intel-deviceplugin-operator
          - name: e2e-iaa-gnr
            targetjob: e2e-iaa
            runner: simics-gnr
            images: intel-iaa-plugin intel-idxd-config-initcontainer accel-config-demo intel-deviceplugin-operator
          - name: e2e-fpga
            runner: fpga
            images: intel-fpga-plugin intel-fpga-initcontainer intel-fpga-admissionwebhook opae-nlb-demo
          - name: e2e-spr
            runner: spr
            images: intel-qat-plugin intel-qat-initcontainer openssl-qat-engine intel-dsa-plugin intel-idxd-config-initcontainer accel-config-demo intel-deviceplugin-operator intel-iaa-plugin crypto-perf intel-gpu-plugin intel-sgx-plugin intel-sgx-initcontainer intel-sgx-admissionwebhook sgx-sdk-demo

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    env:
      TARGET_JOB: ${{ matrix.targetjob || matrix.name }}
      IMAGES: ${{ matrix.images }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Describe test environment
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Images: $IMAGES"
          echo "Target job: $TARGET_JOB"
      - name: Wait for ready state
        run: ../../../../bmetal/actions-bmetal-runstage.sh waitready
      - name: Prepare test environment
        run: ../../../../bmetal/actions-bmetal-runstage.sh prepare
      - name: Run tests
        run: ../../../../bmetal/actions-bmetal-runstage.sh test
